### ISSUE TITLE
Client side instrumentation not working with "next start"

### ISSUE THREAD

**Issue by dmelo** [newrelic/newrelic-node-nextjs#106]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When I run my application with `yarn dev:newrelic` I can see, on New Relic dashboard both server side data and client data (on Browser). But when I run with `yarn start:newrelic`, only server side integration works, browser integration doesn't.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

I expected to see browser instrumentation running on both `dev` and `start` commands

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

On my `package.json` I have:

```
...
   "dev:newrelic": "NODE_OPTIONS='-r @newrelic/next' next dev",
    "build": "next build",
    "start:newrelic": "NODE_OPTIONS='-r @newrelic/next' next start",
...
```

Running with `yarn dev:newrelic`:

Shell 1:

```
❯ yarn dev:newrelic
yarn run v1.22.19
warning ../../package.json: No license field
$ NODE_OPTIONS='-r @newrelic/next' next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/dmelo/proj3/fc/fc-web/.env.local
info  - Loaded env from /home/dmelo/proj3/fc/fc-web/.env
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 665 ms (456 modules)
```

Shell 2:

```
❯ ./nrdiag_x64 -browser-url http://localhost:3000

Check Results
-------------------------------------------------

Success  Browser/Agent/GetSource
Success  Browser/Agent/Detect
See nrdiag-output.json for full results.

No Issues Found

```

Running with `yarn start:newrelic`:

Shell 1:

```
❯ yarn start:newrelic
yarn run v1.22.19
warning ../../package.json: No license field
$ NODE_OPTIONS='-r @newrelic/next' next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/dmelo/proj3/fc/fc-web/.env.local
info  - Loaded env from /home/dmelo/proj3/fc/fc-web/.env
```

Shell 2:

```
❯ ./nrdiag_x64 -browser-url http://localhost:3000

Check Results
-------------------------------------------------

Failure  Browser/Agent/GetSource
1 results not shown: 1 None
See nrdiag-output.json for full results.

Issues Found
-------------------------------------------------
Failure - Browser/Agent/GetSource
We were unable to find the Browser agent script in the HTML source code for http://localhost:3000. If this has not been added to the application yet, follow one of the deployment options suggested in our documentation. However, if the browser script is being loaded via an external file, keep in mind that this can cause issues in collecting the data for New Relic.
See https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent for more information.

```

Also, I see that when running on dev, I have an extract `script` on my html:

```
<script type="text/javascript" src="https://bam.nr-data.net/1/NRBR........."></script>
```

(redacting part of src with ".....")

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

In my case, I've followed the steps to integrate my nextjs application with newrelic. With `yarn dev` the integration will work fine, with `yarn start`, browser integration won't work.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

@newrelic/next: 0.4.0
node: v16.17.1
Next.js: 12.3.2

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mrickard** [comment]
@dmelo I'm sorry to hear that you're having trouble with this integration. Since you've been able to verify that `yarn dev:newrelic` is working for you, have you tried running `yarn build` before `yarn start`? Does that change the behavior?

**Comment by dmelo** [comment]
@mrickard , thanks for the quick response. Yes, I'm doing `yarn build` before running the `start`, on the same code that `yarn dev` is working.

**Comment by dmelo** [comment]
Btw, I was able to reproduce the issue with the https://github.com/newrelic-experimental/newrelic-nextjs-integration repo. If you try just with "yarn dev", it works as expected. BUT, if you do a `yarn build` and then a `yarn start`, then it stops send client side data to New Relic.

**Comment by bizob2828** [comment]
@dmelo this is a known issue #99. In fact I've fixed part of it in the [example app](https://github.com/newrelic-experimental/newrelic-nextjs-integration) you linked.  But the root cause here is that if you have static pages in the Next.js it cannot properly generate the browser agent script because it expects you to be in transaction context.  Transaction context requires active requests but since the pages are built beforehand it'll never be in context.  We're trying to get this work prioritized so please follow #99 for more progress
