### ISSUE TITLE
Getting `Agent is out of date` Alert on latest version

### ISSUE THREAD

**Issue by migolo** [newrelic/newrelic-node-nextjs#110]
I got the latest version v0.4.0 and I get an Alert that the new relic version is out of date.

## Description

The latest version v0.4.0 installs New Relic agent version v9.0.3 which is outdated the latest version is v9.9.0.

## Expected Behavior

To use a supported version.

## Your Environment

<img width="616" alt="Screenshot 2023-02-09 at 18 38 04" src="https://user-images.githubusercontent.com/207846/217971411-98bcd432-8ef7-46d2-bbcd-7ba48e3b6aec.png">
<img width="453" alt="Screenshot 2023-02-09 at 18 37 28" src="https://user-images.githubusercontent.com/207846/217971424-4fb1511a-749b-49cf-b61c-c8332ac53db1.png">

**Comment by bizob2828** [comment]
@migolo you can just run `npm install newrelic@latest`. We tend to only update packages external to agent when there's a minimum needed or we do a semver major bump.
