### ISSUE TITLE
This doesn't work on older browsers (such as Safari 12) because of its use of newer javascript features

### ISSUE THREAD

**Issue by neilgd** [newrelic/newrelic-node-nextjs#118]
When running on older browsers, specifically Safari 12, 13 and 14, the code gives syntax errors because of its use of eg optional chaining (try changing the linting options to eg ecmaVersion: 2015).

It would be great if either 

a) These bits could be altered, or 
b) You could transpile to support earlier versions.

I guess b) would be preferable?

I have a support issue here:

https://forum.newrelic.com/s/hubtopic/aAX8W00000005maWAA/error-on-safari-12-with-next-js-react

Thanks!

**Comment by bizob2828** [comment]
@neilgd this repo contains instrumentation for server side Next.js code.  I'm not sure what Next.js server side code you'd be loading into Safari.  Can you give me a reproduction case please?

**Comment by neilgd** [comment]
Sure - it's the example here:

https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data

**Comment by neilgd** [comment]
I have also tried this way:

https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/pages/_document.tsx

**Comment by neilgd** [comment]
The code injected into the browser includes the following:

```(window.NREUM || (NREUM = {})).loader_config = {
    agentID: "538463274",
    accountID: "3876402",
    trustKey: "3876402",
    xpid: "Vw4AV1JTChADXFZQAAYDUVQ=",
    licenseKey: "NRJS-9fafc6fbb14aa415e44",
    applicationID: "387277470"
};;
(() => {
    var e, t, r = {
.
,
,
 const C = e => ({
                        buildEnv: j.Re,
                        bytesSent: {},
                        customTransaction: void 0,
                        disabled: !1,
                        distMethod: j.gF,
                        isolatedBacklog: !1,
                        loaderType: void 0,
                        maxBytes: 3e4,
                        offset: Math.floor(O._A?.performance?.timeOrigin || O._A?.performance?.timing?.navigationStart || Date.now()),
                        onerror: void 0,
                        origin: "" + O._A.location,
                        ptid: void 0,
                        releaseIds: {},
                        sessionId: 1 == v(e, "privacy.cookies_enabled") ? (0, N.Bj)() : null,
                        xhrWrappable: "function" == typeof O._A.XMLHttpRequest?.prototype?.addEventListener,
                        userAgent: n,
                        version: j.q4
                    }),

.
.
.
```

Note this line:

**`offset: Math.floor(O._A?.performance?.timeOrigin || O._A?.performance?.timing?.navigationStart || Date.now()),`**

which contains the `?.` operator which isn't supported in earlier browsers.

**Comment by bizob2828** [comment]
@neilgd the code you're linking is our browser agent.  This supports the last 10 versions of safari which you can see [here](https://browsersl.ist/#q=last+10+safari+versions). Here's the [doc](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/) which we state which browsers and versions which we support.  I'm going to close this as it's unrelated to Next.js instrumentation.  If you have other issues with the browser agent you can file an issue [here](https://github.com/newrelic/newrelic-browser-agent)
