### ISSUE TITLE
Instrumentation broken in Next.js@13.3.1

### ISSUE THREAD

**Issue by jmartin4563** [newrelic/newrelic-node-nextjs#120]
## Description
In the 13.3.1 release of Next.js, our instrumentation is failing to fully register due to a change in the Next.js' webpack output. Specifically, the render and context modules are now output without setter functions, which means we're unable to apply our monkeypatch.

## Expected Behavior
Versioned tests run successfully on 13.3.1

## Steps to Reproduce
1. `npm run verisoned:major`
2. Observe that tests fail on 13.3.1
3. Observer error messages in the agent log: `Cannot set property renderToHTML of #<Object> which has only a getter` and `Cannot set property getModuleContext of #<Object> which has only a getter`

## Additional context
**Next.js@12 Context output**
<img width="874" alt="Screenshot 2023-04-24 at 2 04 08 PM" src="https://user-images.githubusercontent.com/3333180/234079536-40b45038-21e2-4605-a5de-a91ebea59d4b.png">

**Next.js@13.3.1 Context output**
<img width="808" alt="Screenshot 2023-04-24 at 2 04 43 PM" src="https://user-images.githubusercontent.com/3333180/234079546-8cf686f8-14ea-465d-be6b-c95ea31ee568.png">

**Comment by kdembowski** [comment]
Hey there, would https://github.com/newrelic/newrelic-node-nextjs/pull/124 also cover Next's app directory?
I've been trying to set up log forwarding with it, but it doesn't send any logs at all. Same set up works with pages directory.

**Comment by bizob2828** [comment]
@kdembowski it will not.  Can you please file a separate feature request for this please?

**Comment by kdembowski** [comment]
@bizob2828 I created https://github.com/newrelic/newrelic-node-nextjs/issues/126. 
By "works with pages directory" I meant that exact same configuration of logger+newrelic worked in /pages, while it does not work with the new app router introduced in Next 13 (unless I'm doing something wrong).
Let me know if you need anything else
