### ISSUE TITLE
ENV VARs are `undefined`

### ISSUE THREAD

**Issue by wsfuller** [newrelic/newrelic-node-nextjs#130]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

`newrelic.js` supports the use of env vars like [NEW_RELIC_APP_NAME](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#app_name) using the [Next.js env var solution](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables) these values are coming back `undefined`. There doesn't seem to be a working example or explanation on how to setup New Relic with Next.js using env vars natively. 

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

Would expect either an example or documentation on this or the values to propagate. 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Use a `.env` or `.env.local` to populate dynamic values for use in New Relic and values will be undefined

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by wsfuller** [comment]
How would someone run `NODE_OPTIONS='-r @newrelic/next' next start` in different environments? Say I only wanted this to run in production and not staging if this is being loaded before anything else?

**Comment by mrickard** [comment]
@wsfuller Would you be able to post a simple repro case for us? 

As for the starting in different environments, that'd largely depend on how you've set up your infrastructure and where it's hosted. If you're using a different start command or start script, it'd be straightforward. If you're limited to using the same start command in all environments, that'd be trickier. (We're aware that some hosts don't give access to the start or build commands.)

**Comment by wsfuller** [comment]
That's ultimately what I'm trying to understand with the instructions. With being asked to load the library this way (`NODE_OPTIONS='-r @newrelic/next' next start`) I don't see how to access the Next environment variables or a way to really control how or when the library is instantiated in conjunction with environment variables.

As of right now pretty limited to using the default start up scripts with out environments.

One way I've been able to get any environment variables to populate is:

```
newrelic.js

require(dotenv).config();

exports.config = {
  app_name: [process.env.NEW_RELIC_APP_NAME],
  license_key: process.env.NEW_RELIC_LICENSE_KEY,
  ...
}
```

```
 next.config.js

require('@newrelic/next)

const nextConfig = {...}
```

```
package.json

{
  ...
  "scripts": {
    "dev": "next dev"
  }
}
```


The repo case would be doing a very basic Next.js installation:

[Referencing this New Relic blog post](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data)

- Generate Next.js project: `npx create-next-app@latest`
- Install New Relic Node Agent and New Relic Next Agent: `yarn add newrelic @newrelic/next`
- Modifiy dev and start scripts accordingly: `"dev": "NODE_OPTIONS='-r @newrelic/next' next",`
- Add `newrelic.js` config at the root with name and license key shown above

**Comment by wsfuller** [comment]
Also seeing an issue using the official [Next.js Docker documentation](https://nextjs.org/docs/app/building-your-application/deploying#docker-image). Nothing seems to be sent to New Relic using their [with-docker example](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile). Using a static `newrelic.js` file and nothing being influenced by env vars doesn't seem like this library is compatible with the Next defaults there. Am able to see throughput using `next dev`

**Comment by mrickard** [comment]
@wsfuller I've attempted a repro with `npx create-next-app@latest`, installing `newrelic`, `@newrelic/next`, and  `dotenv`. modified the dev and start scripts, and found that environment variables defined in `.env` are picked up both in `dev` and `start`. I didn't have to modify `newrelic.js` or `next.config.js`.

One thing you could try is adding `dotenv` to the start or dev scripts before `newrelic`: 
`"dev": "NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next dev"`
`"start": "NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next start"`

Do you have a ticket open with Support?

**Comment by wsfuller** [comment]
So I've used a couple different machines, latest library versions, using `node v18.16.0` and failures/success are reproducible. Looks like the success in your example was an explicit `dotenv` installation. This was never installed explicitly before but was able to successfully require in that previous example. Going to step through fresh install, error outputs, and where things wound up. 

Fresh install:

- `npx create-next-app@latest`
  - `"next": "13.4.7"` 
- `yarn add newrelic @newrelic/next`
  - `"@newrelic/next": "^0.5.2"`, `"newrelic": "^10.3.1"`
- create `newrelic.js`
  - Set up from [newrelic.js example](https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/newrelic.js)
    - `exports.config = { app_name: [process.env.NEW_RELIC_APP_NAME], license_key: process.env.NEW_RELIC_LICENSE_KEY}` 
- create `.env.local`
  -  `NEW_RELIC_APP_NAME="App Name"` `NEW_RELIC_LICENSE_KEY="12345"` 
- update `dev` script `"dev": "NODE_OPTIONS='-r @newrelic/next' next"` 
- run `yarn dev`

<img width="420" alt="Screenshot 2023-06-26 at 10 04 07 AM" src="https://github.com/newrelic/newrelic-node-nextjs/assets/3144419/80088ac7-7639-4491-ba66-9d8d91e4dcb1">


Output:
```
yarn dev
yarn run v1.22.19
$ NODE_OPTIONS='-r @newrelic/next' next
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at onNextTick (/Users/.../node_modules/newrelic/lib/agent.js:245:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
```

---

Update from `.env.local` to `.env`

Same output as above

---

- Keeping with `.env`
- Updating dev script to `"dev": "NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next"`

Output:

```
yarn dev
yarn run v1.22.19
$ NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'dotenv/config'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1431:5)
    at loadPreloadModules (node:internal/process/pre_execution:606:5)
    at setupUserModules (node:internal/process/pre_execution:118:3)
    at prepareExecution (node:internal/process/pre_execution:109:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:37:3)
    at node:internal/main/run_main_module:10:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v18.16.0
error Command failed with exit code 1.
```

---

- keeping `.env`
- keeping recent dev script change
- `yarn add dotenv`

Output:

```
yarn dev
yarn run v1.22.19
$ NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/stevefuller/development/personal/new-relic-test/.env
- event compiled client and server successfully in 205 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 127 ms (20 modules)
```


--- 

Looks like `.env.local`, fails to load variables when switching back. This is a bummer in that we leverage this for local development according to [Next.js Configuring Environment Variables](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#loading-environment-variables) and we lose the ability to override defaults from the `.env`. So far the only way to natively use `.env.local` was the example above 😞 

I do have a support ticket open on this issue and from the last response we've linked the two

**Comment by wsfuller** [comment]
@mrickard Following up on the Docker portion looks like there is some history I'm uncovering to get this package to work with Docker and the [with-docker example](https://github.com/vercel/next.js/tree/canary/examples/with-docker)

Starting point is [Forum post, Node Next.js with @newrelic/next and outputStandalone](https://forum.newrelic.com/s/hubtopic/aAX8W0000008d6sWAA/node-nextjs-with-newrelicnext-and-outputstandalone) and currently working through different solutions

**Comment by wsfuller** [comment]
Decided not to use this option and instead using `docker-compose` with multiple `newrelic.js` files for each environment.

[Wrote an article](https://medium.com/@wsfuller/new-relic-next-js-backend-observability-with-docker-f6c61d87aea3) that goes over most of everything. Closing this out as the solution chosen in the article is what fits our needs the best and there are tons of ways to solve this problem. Thank you for the help really appreciate your time and attention to this matter and providing a workable solution.
