### ISSUE TITLE
Slack invite link has expired

### ISSUE THREAD

**Issue by mkotamies** [newrelic/newrelic-node-nextjs#146]
## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
Slack invite link should work for users and let new users to request access

## Steps to Reproduce
Click [the invite link](https://github.com/newrelic/newrelic-node-nextjs/blob/d6cb190b8deb300e4c8dd0914781e823fef9c099/CONTRIBUTING.md?plain=1#L40) and see the error "link is no longer active". I have attached a screenshot to the issue

## Your Environment
* Browser is Chrome

## Additional context

<img width="628" alt="Screenshot 2023-08-08 at 11 31 45" src="https://github.com/newrelic/newrelic-node-nextjs/assets/2474092/47add64b-0cd0-48d8-a15e-d6cb7a9d7936">

**Comment by bizob2828** [comment]
thanks for bringing this to our attention @mkotamies.  It turns out we've decommissioned this slack team.  If you need support you can go to the [forum here](https://forum.newrelic.com/s/category/Category__c/Default).  We will be getting this updated en masse at a later date.

**Comment by nareshNishad** [comment]
@bizob2828 I want to contribute and if you don't mind assigning this to me, will remove Slack and insert the forum joining info.
Thanks in advance.

**Comment by bizob2828** [comment]
@nareshNishad sure you can PR this, not a problem
