### ISSUE TITLE
Support Edge Runtime

### ISSUE THREAD

**Issue by jordanvector** [newrelic/newrelic-node-nextjs#157]
## Is your feature request related to a problem? Please describe.
Currently it appears that both the newrelic-node-nextjs and the newrelic-node packages depend on a number of a nodejs native packages that the edge runtime does not support, here is an incomplete list I can tell so far

            fs,
            path,
            child_process,
            http,
            https,
            os,
            zlib,
            module,
            worker_threads,
            dns,
            querystring,
            crypto,
            stream,
            constants,
            net,
            tls,
            node_gyp,
            npm

One big reason for edge runtime compatiability is:

Cloudflare pages only supports edge runtime for next, so currently if we want to host on Cloudflare pages + next, we cannot use newrelic.

## Feature Description
newrelic + @newrelic/next packages compatibility 

## Additional context
Edge Runtime - https://vercel.com/blog/introducing-the-edge-runtime
Edge/Nodejs Runtimes - https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
## Priority
Nice to Have

**Comment by bizob2828** [comment]
Product manager notes: This will have to be its own product, similarly to how we have a lambda layer.  Our agent cannot function in the edge due to it not being Node.js.

**Comment by w33ts** [comment]
+1 to this. We're working on an application that exists fully in on the edge and would love to integrate NR into it! Specifically, we are using Next.js on Cloudflare Pages, but I'm not sure if it supports OpenTelemetry in Edge Runtime mode.

**Comment by piotrcichosz** [comment]
+1

**Comment by bizob2828** [comment]
The edge runtime is a pared down version of Node.js and also operates as a Function as a Service. This would have to be an entirely new product offering.  This is currently not on our roadmap. I will close this feature request.
