### ISSUE TITLE
routing is not working

### ISSUE THREAD

**Issue by nisarg2023** [newrelic/newrelic-node-nextjs#158]
**layout.tsx**
import { Providers } from "@/redux/provider";
import "../styles/globals.css";
import type { Metadata } from "next";
import RouterGard from "@/components/RouterGard/RouterGard";
import ToastNotification from "@/components/toastNotification/ToastNotification";
import ColorDefine from "@/components/Common/ColorDefine";
import Script from "next/script";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Dyshez",
  description: "description",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src={`${process.env.NEXT_HOST_NAME}/assets/js/newrelic.js`}
        />
      </head>
      <body>
        <main className="relative">
          <ColorDefine />
          <Providers>
            <ToastNotification />
            <RouterGard>{children}</RouterGard>
          </Providers>
        </main>
      </body>
    </html>
  );
}

routing does not work when I add a new relic browser script but without the new relic script it works properly
I copied and past script from the new relick dashboard and removed <script> tage

**Comment by nisarg2023** [comment]
@mrickard  I try this solution but it will connect me to APM & service. But actually I want to connect my next js 13 app with Browser 
I connect my next js 13 app with Browser successfully but problems in routine a routine is not work properly 

And I also try to connect my react js app with Browser it work properly

**Comment by mrickard** [comment]
@nisarg2023 This repository is meant to work with the New Relic Node Agent (APM), which can inject the New Relic browser agent for full end-to-end APM. If you _don't_ want APM and just want browser monitoring, then you'll probably want not to use this project, and just inject the browser agent. If you have an issue in getting that to work, then you may want to open an issue in  https://github.com/newrelic/newrelic-browser-agent
