### ISSUE TITLE
New Relic Nest JS Monitoring

### ISSUE THREAD

**Issue by ranga0001** [newrelic/newrelic-node-nextjs#160]
One of our application using Nest JS and we have instrumented new relic agent but Pod fails to come up

Dockerfile 

WORKDIR /var/www/html
    
COPY ./package.json ./package-lock.json ./
COPY ./dist/apps/platform-service/ ./
COPY ./node_modules/ ./node_modules/

RUN npm install newrelic

ENV NEW_RELIC_APP_NAME="dev-test-app" \
    NEW_RELIC_LICENSE_KEY="xxxx" \
	NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_APPLICATION_LOGGING_ENABLED=false \
    NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false \
    NEW_RELIC_ALLOW_ALL_HEADERS=true \
    NEW_RELIC_LOG_ENABLED=true \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_ATTRIBUTES_EXCLUDE='["request.headers.cookie", "request.headers.authorization", "request.headers.proxyAuthorization", "request.headers.setCookie*", "request.headers.x*", "response.headers.cookie", "response.headers.authorization", "response.headers.proxyAuthorization", "response.headers.setCookie*", "response.headers.x*"]'
#    NODE_OPTIONS="--require @newrelic/next"

EXPOSE 3000

CMD ["node", "-r", "newrelic", "--enable-source-maps", "./app.js"]

Please suggest how to Monitor Nest JS apps. We were able to monitor NextJS but not with Nest JS

**Comment by bizob2828** [comment]
We automatically instrument nestjs but in (New Relic Node.js agent)[https://github.com/newrelic/node-newrelic]. This repository only contains a standalone instrumentation package for Next.js.
