### ISSUE TITLE
Replace deprecated getInitialProps for error logging

### ISSUE THREAD

**Issue by TimRuebP** [newrelic/newrelic-node-nextjs#171]
## Is your feature request related to a problem? Please describe.
The official New Relic Next.js docs state that you should use getInitialProps on the _error.js page to forward errors to NR. However, this function is deprecated by Next.js. 

## Feature Description
Next.js support by New Relic should use some other function than getInitialProps to forward errors. 
Official guide: https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data#toc-sending-detailed-error-information-to-new-relic 
Next.js deprecation notice: https://nextjs.org/docs/pages/api-reference/functions/get-initial-props

## Describe Alternatives
-/-

## Additional context
-/-

## Priority
As soon as Next.js decides to get rid of getInitialProps, New Relic error logging won't work anymore.

**Comment by ygerass** [comment]
We cannot prioritize this feature at the moment. Our recommendation is to rely on the experimental instrumentationHook feature of Next.js, use OpenTelemetry and send the data to New Relic via OTLP ([gist reference](https://gist.github.com/bizob2828/a7d52ac69b7db6d8508c865aafa0b62b)).
