### ISSUE TITLE
Add Next.js 14 support for App router

### ISSUE THREAD

**Issue by abrahamgr** [newrelic/newrelic-node-nextjs#173]
## Is your feature request related to a problem? Please describe.
My team already uses Next.js with Newrelic integratin, recently we moved to Next.js 14.1 and I started to see in the logs `Next.js middleware instrumentation only supported on >=12.2.0 <=13.4.12, got 14.1.0`.

## Feature Description
It would be nice to have Newrelic fully supported in latest version of Next.js

## Describe Alternatives
If middleware instrumentation is not supported it would be nice to turn off by passing props.

## Additional context
I'd like to integrate Newrelic using the AMP, integrating Browser monitoring using `getBrowserTimingHeader` and get support for middleware.

## Priority
Really Want

**Comment by bizob2828** [comment]
@abrahamgr our testing shows Next.js 14 works.  During research in the fall of 2023 we also found that app router works.  We are doing more research soon around officially supporting app router which means perhaps introducing capture more segments/spans.  The error message you mention is around middleware.  Next.js has change significantly since we added our instrumentation and the middleware function should only be a small part of the observability.

**Comment by agwermann** [comment]
@bizob2828, thanks for you response. I also faced the same issue when setting up NewRelic with Next AppRouter structure with both server and client side (I only tested in Next 13). It is really nice to hear that you were able to make it work in Next 14.

Can you share the details to make it work in Next 14 or let us know once you have an official release with support to newest versions of NextJs?

**Comment by bizob2828** [comment]
@agwermann we didn't do anything. we just never had tests against app router.  Looking at it more closely we will only name transactions and keep the appropriate async context.  `getServerSideProps` is no longer a thing so we will not capture spans for it. Also we no longer instrument middleware as it runs in a worker thread and our agent cannot propagate to child threads, however that's unrelated to app router.  Also api routes no longer seem relevant as you make calls to functions within your page components so we will not track API calls as spans.  Is there something you expect to see that you're not currently?

**Comment by abrahamgr** [comment]
@bizob2828 thanks, good to know.
I have one more question, reading the Next.js docs I see they suggest to register the instrumentation on the [instrumentation.ts](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation) file, something like:

```typescript
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('@newrelic/next')
  }
```

Is this now the best place to setup New Relic? or is better setting Node.js to pre-load @newrelic/next as this [guide](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data) mentions?
