### ISSUE TITLE
load-externals.js file is not included in @newrelic/next 0.8.0

### ISSUE THREAD

**Issue by abrahamgr** [newrelic/newrelic-node-nextjs#182]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Following the instructions in 0.8.0 version to [Load Instrumentation](https://github.com/newrelic/newrelic-node-nextjs?tab=readme-ov-file#load-instrumentation) the file **load-externals.js** is not included in this version published to npm.

## Expected Behavior
File **load-externals.js** should exists in that version.

## Steps to Reproduce

After install the package `npm install @newrelic/next` as you can see that file is not included.

<img width="235" alt="image" src="https://github.com/newrelic/newrelic-node-nextjs/assets/9330588/13ba8fe2-5aef-4fec-98d2-d60f5320e980">

## Your Environment

Node: 20.10.0
Next.js: 14.1.3

**Comment by mrickard** [comment]
@abrahamgr Sorry to hear you're having troubles. I see that 0.8.0 was released two weeks ago, while the current README here on GitHub was updated last week. This will be available in the next release, but for the meantime I'd recommend following the README that was current when 0.8.0 was released: https://github.com/newrelic/newrelic-node-nextjs/blob/e7bc0db0599713036c2d63b70f960ef86ccde9b0/README.md
