### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Pranav2111** [newrelic/newrelic-node-nextjs#195]
- I am using browser agent for my Next JS application. I have integrated it using APM. I am getting following error very frequently in my application "Cannot read properties of undefined (reading 'length')" .
- I am attaching the screenshot of my sentry issue for reference.
- I am using Node JS agent for APM
- I have referred official doc to setup browser agent for my Next JS application. Here is the link for reference - [https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data)

![Screenshot from 2024-05-16 13-09-06](https://github.com/newrelic/newrelic-node-nextjs/assets/56624008/93121b4e-b21d-4ea2-a5f3-3204d78a16fd)

![Screenshot from 2024-05-16 13-10-00](https://github.com/newrelic/newrelic-node-nextjs/assets/56624008/78ca8056-be06-485b-be24-31a6684858c9)

**Comment by mrickard** [comment]
Sorry to hear you're having trouble @Pranav2111 . This looks like it's being thrown from the browser side, so I'm going to transfer this to that team. (This repo's owned by the APM side Node Agent team.)

**Comment by mrickard** [comment]
@Pranav2111 I'm not able to move this, but the Browser team is working on this issue. Could you open this issue [on their repo](https://github.com/newrelic/newrelic-browser-agent)? Thank you!

**Comment by cwli24** [comment]
(browser agent) bug created - https://new-relic.atlassian.net/browse/NR-270488

**Comment by metal-messiah** [comment]
Browser agent bug fix PR -- https://github.com/newrelic/newrelic-browser-agent/pull/1039
