### ISSUE TITLE
Node 20.14.0 version not taking "-r" option in startup scripts.

### ISSUE THREAD

**Issue by suryaaemops** [newrelic/newrelic-node-nextjs#211]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Node 20.14.0 version not taking "-r" option in startup scripts.

NODE_OPTIONS='-r @newrelic/next' next dev

Throwing  error as below:

pnpm/nodejs/20.14.0/bin/node: --r= is not allowed in NODE_OPTIONS

## Expected Behavior

we expect to run with node options -r.

## Steps to Reproduce

Try starting the app as below

"scripts": {
    "dev": "NODE_OPTIONS='-r @newrelic/next' next dev",
    "build": " NODE_OPTIONS='-r @newrelic/next next build",
    "start": "NODE_OPTIONS='-r @newrelic/next next start",

Throwing  error as below:

pnpm/nodejs/20.14.0/bin/node: --r= is not allowed in NODE_OPTIONS

**Comment by bizob2828** [comment]
this is how you inject the instrumentation though. I'll take a look

**Comment by bizob2828** [comment]
@suryaaemops i think your issue is that you may have two hyphens `-`.  Looking at that error 

```
pnpm/nodejs/20.14.0/bin/node: --r= is not allowed in NODE_OPTIONS
```

it shows `--r` but should be `-r`
