### ISSUE TITLE
Newrelic not showing Webtransactions and Error data. showing CPU and Memory only

### ISSUE THREAD

**Issue by suryaaemops** [newrelic/newrelic-node-nextjs#212]
We have integrated newrelic with our Nextjs app.
following the urls
1) https://www.npmjs.com/package/@newrelic/next
2)https://github.com/newrelic/node-newrelic

## Expected Behavior

We are not seeing Webtransaction and Error metrics. We only see CPU and Memory metrics

this is the log 

https://rpm.newrelic.com/accounts/2395010/applications/1054322302","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:33:50.080Z","msg":"Valid event_harvest_config received. Updating harvest cycles. {\"report_period_ms\":5000,\"harvest_limits\":{\"error_event_data\":8,\"log_event_data\":0,\"analytic_event_data\":833,\"custom_event_data\":250}}"}
{"v":0,"level":30,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:33:50.106Z","msg":"Span streamer connected","component":"base-span-streamer"}
{"v":0,"level":30,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:33:50.106Z","msg":"Agent state changed from connected to started."}
{"v":0,"level":30,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:33:51.106Z","msg":"Starting initial 1000ms harvest."}
{"v":0,"level":40,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:33:51.109Z","msg":"send() is not currently supported on streaming span event aggregator. This warning will not appear again this agent run.","component":"streaming-span-event-aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"sbhupat-ltmkxf3.internal.salesforce.com","pid":12180,"time":"2024-07-16T12:34:21.397Z","msg":"Span streamer disconnected","component":"base-span-streamer"}

wanted to know if  it is the problem of integration config or Newrelic?

Below is our node and newrelic version details:

Node version : v20.14.0
"@newrelic/next": "0.9.0",
    "newrelic": "^11.18.0",

**Comment by bizob2828** [comment]
@suryaaemops for issues like this, I recommend leveraging our support team over at [support.newrelic.com](https://support.newrelic.com/s/) which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs). At first glance it appears you're using infinite tracing and it is not working for some reason. I'm going to close this issue because it's going to be very hard to triage in the context of Github issue.
