### ISSUE TITLE
New Relic Browser Monitoring Failure - Next.js + Docker + New Relic

### ISSUE THREAD

**Issue by matt-greatminds** [newrelic/newrelic-node-nextjs#214]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I have followed numerous documents outlining how to implement New Relic in a Next.js app using the App Router.  I can get it working when running `npm run dev`, but when I build for production and run in a Docker container the browser agent script fails to load.

`getBrowserTimingHeader()` returns `<!-- NREUM: (1) -->`

I have confirmed both NewRelic License and App name are populated and available for the application code.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

The expected behavior is that the `getBrowserTimingHeader()` method returns the script that is required to be loaded for browser_monitor to work.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

Next.js: 14.2.5
React: 18.3.1
NewRelic: 11.23.2
@NewRelic/next: 0.10.0
@types/newrelic: 9.14.4
Node: 20.2.0
Docker: 
![image](https://github.com/user-attachments/assets/40a3da3c-87ea-4f0c-8ae0-fd8baa1e5f16)

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context
Layout.tsx
![image](https://github.com/user-attachments/assets/6f22faa0-3e14-496e-aff8-cb5aaffd49dd)

Next Config
![image](https://github.com/user-attachments/assets/fcbfb223-6872-42a0-b9c6-ae95545c2c19)

Dockerfile 
![image](https://github.com/user-attachments/assets/274bd1c1-90ac-47bd-a572-03e93381a938)

docker run command
```
docker run -p 3000:3000 -e NEW_RELIC_LICENSE_KEY=<myLicenseKey> -e NEW_RELIC_APP_NAME='<myAppName>' -e NEW_RELIC_LOG_ENABLED=true example-for-newrelic-ticket
```

Agent Logs snapshot
![image](https://github.com/user-attachments/assets/fe1778a5-56ae-4a4e-9f81-1b747478aecc)

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mrickard** [comment]
@matt-greatminds Sorry to hear that you're having trouble. The `(1)` error occurs when the agent is attempting to inject the browser timing header, but there's no transaction involved--the kind of situation you'd see during a build step, where there wouldn't be an active web transaction. To address this, we added an `allowTransactionlessInjection` flag, and you can see [an example here](https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router/app/layout.js#L20-L23). That's linked from the [FAQs doc](https://github.com/newrelic/newrelic-node-nextjs/blob/main/docs/faqs/browser-agent.md) in our NextJs instrumentation repo.
