### ISSUE TITLE
404 page requests can result in an extra *.js transaction

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-nextjs#50]
With the default 404 setup for the Next.js blog tutorial, an additional `/*.js` transaction appears along with the `GET//404`.

Example:

URL: `/_next/static/chunks/pages/_error-2280fa386d040b66.js`
request.headers.referer: http://localhost:3000/does/not/exist (the original URL)

It seems like there can be multiple requests to the error file for a 404 but appears these may stop (due to caching?).

Seeing `*.js` may be confusing, particularly since this time can be slower than just the 404 serving as well so we should ideally find a way to handle these so it is straightforward.

**Comment by bizob2828** [comment]
It's worth noting these pages can be customize these pages https://nextjs.org/docs/advanced-features/custom-error-page

**Comment by jsumners-nr** [comment]
> With the default 404 setup for the Next.js blog tutorial

What is this tutorial? Do you have a link?

Do we have a minimal reproduction and set of steps that trigger this issue?

**Comment by bizob2828** [comment]
@jsumners-nr it is [this](https://nextjs.org/learn-pages-router/basics/data-fetching/blog-data)

**Comment by kmudduluru** [comment]
Closing this issue as we

**Comment by kmudduluru** [comment]
Closing this issue as we do not have any recent requests for this.
