### ISSUE TITLE
My  codestream.xml keeps changing when i save my project

### ISSUE THREAD

**Issue by bret1234** [newrelic/newrelic-node-nextjs#58]
I'm using Jetbrains Webstorm, and i keep having my codestream.xml file change, when i save. BUT, it's committed to github ok, tho, it changes again. 
The "Change" is in the "value" in my <option> part or the script to have in the file....

So I'm not too sure if this is Jetbrains, it seems like NewRelic

**Comment by coreyarnold** [comment]
Looks like the CodeStream team helped get this sorted out via [twitter](https://twitter.com/EmmerichBret/status/1522602458786283520). Happy coding!
