### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by hosseini44444** [newrelic/newrelic-node-nextjs#59]
## Is your feature request related to a problem? Please describe.
Not really

## Feature Description
A basic example project with both backend and frontend instrumentation

## Additional context
Also, can be added to Next.js examples

## Priority
Nice to Have

**Comment by Sharan-rupeek** [comment]
Can we have an example for setting up newrelic node agent in nextjs app without custom server file. Right now the transactions are shown under *, *.js and *.png without the custom server file

**Comment by bizob2828** [comment]
@hosseini44444 we have an example app within the repo that you can see our plugin in action via testing: https://github.com/newrelic/newrelic-node-nextjs/tree/main/tests/versioned/app.

**Comment by bizob2828** [comment]
We discussed including the browser snippet code into the app and add a README to `tests/versioned/app`.  Update the root README that links to the "sample" app.
