### ISSUE TITLE
Allow customisation of distributed tracing allowed_origins with getBrowserTimingHeader()

### ISSUE THREAD

**Issue by KGAdamCook** [newrelic/newrelic-node-nextjs#65]
## Is your feature request related to a problem? Please describe.
For Browser Applications we are able to define allowed origins for CORS, https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/#cors-configure. 
However when using "getBrowserTimingHeader()" we are unable to provide the script with such customisation. 

## Feature Description
A clear and concise description of the feature you want or need.
Further customisation of the getBrowserTimingHeader() that allows for CORS configuration.

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to? 
via one.newrelic.com we are able to configure CORS and setup our own <script /> tag manually. 
https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/#cors-configure. 

## Additional context
Add any other context here.

## Priority
Please help us better understand this feature request by choosing a priority from the following options:
Really Want

**Comment by bizob2828** [comment]
We need to determine what would be required to get this setup with the browser agent.  Per the [docs](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/#requirements), it looks like other language agents do support this.

**Comment by hashlash** [comment]
Currently, I can set the allowed origins via the Browser application setting and the [client-side instrumentation](https://github.com/newrelic/newrelic-node-nextjs#client-side-instrumentation) do the rest.

**Comment by KGAdamCook** [comment]
@hashlash there is no such setting on the APM app settings page

**Comment by hashlash** [comment]
@KGAdamCook the CORS setting should be the same as what you've described

> via one.newrelic.com we are able to configure CORS and setup our own <script /> tag manually.
https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/#cors-configure.

But instead of manually copy-pasting the script, I use the node APM and let the [client-side instrumentation](https://github.com/newrelic/newrelic-node-nextjs#client-side-instrumentation) do the rest.

If you've created your Browser Application using copy-paste method, you might want to recreate it with "Enable via New Relic APM"

**Comment by bizob2828** [comment]
@KGAdamCook I know it's been a while since this request but it looks like @hashlash comments explain how to do this, do you still need this feature request?
