### ISSUE TITLE
Plugin fails to register instrumentation for next-server when using standalone Next.js server

### ISSUE THREAD

**Issue by bizob2828** [newrelic/newrelic-node-nextjs#69]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

It was discovered when trying to update the [with-docker Next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-docker) that even after figuring out how to get the plugin added to the container, the plugin instrumentation wasn't registering properly.  This is because in the [standalone server.js](https://github.com/vercel/next.js/blob/canary/packages/next/build/utils.ts#L1217) it requires the next-server as `next/dist/server/next-server` and our plugin expect the first require of next-server to be `./next-server` because that's how it is done in the [next CLI](https://github.com/vercel/next.js/blob/canary/packages/next/server/next.ts#L6).

## Expected Behavior
New Relic Next.js plugin should register server instrumentation with standalone server.

## Steps to Reproduce
```
npm i @newrelic/next
next build
node -r @newrelic/next .next/standalone/server.js
```

* ex: Operating System and version:

**Comment by sebastianmulders** [comment]
Thanks for your work on this @bizob2828. I was hoping that your fix would solve my problem with Next's standalone output, as described [here on the NR support forums](https://discuss.newrelic.com/t/next-js-with-newrelic-next-and-outputstandalone/184834). But unfortunately, updating @newrelic/next did not help. I've updated [my demo repository](https://github.com/sebastianmulders/nextjs-newrelic-standalone) that (still) outlines what goes wrong (`Cannot find module '@newrelic/next'` in the container).

Not sure if I've misunderstood this issue (and fix), perhaps it's unrelated, or I'm missing something else.

**Comment by bizob2828** [comment]
Hi @sebastianmulders I shared this with the support. Here's the updated docker file to get the plugin working https://gist.github.com/bizob2828/0fa170a9194838cab5dc8fbb00109425

**Comment by sebastianmulders** [comment]
Hey @bizob2828, thanks for your reply. Good suggestion to explicitly install @newrelic/next in the Dockerfile again, it does indeed work this way. Feels suboptimal though. Especially since it pulls in all other dependencies too (or at least, tries to, as I ran into a couple 401's due to pulling in private packages). It also delays the pipelines a fair bit (due to fetching + resolving packages twice).

But I guess it'll do for now!

**Comment by bizob2828** [comment]
> Hey @bizob2828, thanks for your reply. Good suggestion to explicitly install @newrelic/next in the Dockerfile again, it does indeed work this way. Feels suboptimal though. Especially since it pulls in all other dependencies too (or at least, tries to, as I ran into a couple 401's due to pulling in private packages). It also delays the pipelines a fair bit (due to fetching + resolving packages twice).
> 
> But I guess it'll do for now!

Yea it's not great but this is a demo application so I didn't want to invest a lot of time in it.  I noticed towards the end it copies the standalone server and the package.json and it has the `@newrelic/next` plugin if you had installed before building the container, but for some reason which I could not figure out it was not copying the installed dependencies.  This has multiple layers and it had exhausted my docker triage chops so I opted for this easy solution.

**Comment by Nargonath** [comment]
I'm facing the same issue and to my understand the problem is due to NextJS `Output File Tracing` feature. This feature determines heuristically which files are needed for your project to run and copies them over during build. However usually you don't import/require `@newrelic/next` package into your application thus it's ignored by OFT feature. You can fix it either by installing the dependencies again after build as you did or require that package in your `_document.tsx` `getInitialProps`. It will be inserted by NextJS on build.

**Comment by sebastianmulders** [comment]
@Nargonath thanks for sharing your insights. I'd say you only need to be careful of not pulling in a bunch of dependencies in the bundle. This is also mentioned in [the installation instructions](https://github.com/newrelic/newrelic-node-nextjs#installation) of `@newrelic/next`.

We've taken the route of using `unstable_includeFiles` and include all `@newrelic/next` related deps this way. A bit verbose and likely to break in the future (due to it being unstable), but for now I think it's the best option.

```
import type { PageConfig } from 'next';

export const config: PageConfig = {
  unstable_includeFiles: [
    'node_modules/@newrelic/next/**/*.+(js|json)',
    'node_modules/newrelic/**/*.+(js|json)',
    'node_modules/semver/**/*.+(js|json)',
    'node_modules/json-stringify-safe/**/*.+(js|json)',
    'node_modules/readable-stream/**/*.+(js|json)',
    'node_modules/inherits/**/*.+(js|json)',
    'node_modules/util-deprecate/**/*.+(js|json)',
    'node_modules/lru-cache/**/*.+(js|json)',
    'node_modules/yallist/**/*.+(js|json)',
    'node_modules/async/**/*.+(js|json)',
    'node_modules/concat-stream/**/*.+(js|json)',
    'node_modules/buffer-from/**/*.+(js|json)',
    'node_modules/https-proxy-agent/**/*.+(js|json)',
    'node_modules/debug/**/*.+(js|json)',
    'node_modules/ms/**/*.+(js|json)',
    'node_modules/agent-base/**/*.+(js|json)',
    'node_modules/@tyriar/fibonacci-heap/**/*.+(js|json)',
  ],
};
```

**Comment by Nargonath** [comment]
Sure you're welcome @sebastianmulders. Thank you for sharing your solution as well. I looked into this solution at some point but it felt brittle to have to list the dependencies of one of your dependencies yourself. If the package authors decide to change the dependencies then your code will break. I even had errors because NextJS was trying to execute file operations on folders for some reason 🤷 .

Do you export that configuration in all of your pages?

Do you get errors in your docker container regarding instrumentation plugins such as:

```json
{
  "v": 0,
  "level": 40,
  "name": "newrelic",
  "hostname": "462d1e7aced0",
  "pid": 1,
  "time": "2022-09-09T09:56:05.054Z",
  "msg": "Failed to load instrumentation for @newrelic/aws-sdk {\"code\":\"MODULE_NOT_FOUND\",\"requireStack\":[\"/app/node_modules/newrelic/lib/shimmer.js\",\"/app/node_modules/newrelic/lib/uninstrumented.js\",\"/app/node_modules/newrelic/lib/agent.js\",\"/app/node_modules/newrelic/index.js\",\"internal/preload\"]}",
  "component": "shimmer"
}
```
This looks like errors from the OFT feature but not sure.

**Comment by sebastianmulders** [comment]
> I looked into this solution at some point but it felt brittle to have to list the dependencies of one of your dependencies yourself.

Very true. It's not optimal, feels brittle indeed, but comparing the other options we have, quite workable.

> Do you export that configuration in all of your pages?

No, just pages/index.tsx. It's just that these deps end up in the actual container. The server is started with `node -r @newrelic/next server.js` so I think it's not needed to set this in every page.

> Do you get errors in your docker container regarding instrumentation plugins such as:
> 
> ```json
> {
>   "v": 0,
>   "level": 40,
>   "name": "newrelic",
>   "hostname": "462d1e7aced0",
>   "pid": 1,
>   "time": "2022-09-09T09:56:05.054Z",
>   "msg": "Failed to load instrumentation for @newrelic/aws-sdk {\"code\":\"MODULE_NOT_FOUND\",\"requireStack\":[\"/app/node_modules/newrelic/lib/shimmer.js\",\"/app/node_modules/newrelic/lib/uninstrumented.js\",\"/app/node_modules/newrelic/lib/agent.js\",\"/app/node_modules/newrelic/index.js\",\"internal/preload\"]}",
>   "component": "shimmer"
> }
> ```

I don't see such an error, everything seems to be working quite well. There only seems to be a permission error regarding `/app/newrelic_agent.log` but I haven't really looked into that yet.

**Comment by Nargonath** [comment]
> No, just pages/index.tsx. It's just that these deps end up in the actual container. The server is started with node -r @newrelic/next server.js so I think it's not needed to set this in every page.

Alright, makes sense thank you.

> I don't see such an error, everything seems to be working quite well. There only seems to be a permission error regarding /app/newrelic_agent.log but I haven't really looked into that yet.

I think this error came from missing files due to NextJS OFT feature as I only `require`d the packages in my `_document.tsx` but didn't use `unstable_includeFiles` or reinstall the dependencies again in the Dockerfile. I just tried reinstalling them in the Dockerfile and the warning just vanished. I added also `npm prune --production` to remove any dependencies that is not needed. I still have one more error to fix but I expect it to be the same reason: `"Not adding native metric sampler.", "Cannot find module '/app/node_modules/@newrelic/native-metrics/build/Release/_newrelic_native_metrics-9_0_0-native_metrics-93-linux-x64.node'"`. 

FWIW regarding your log permission problem, I had similar issue but I didn't want NR to log into a file anyway so I added this to my `newrelic.config.js`:

```js
exports.config = {
  // ...other configs
  logging: {
    /**
     * Level at which to log. 'trace' is most useful to New Relic when diagnosing
     * issues with the agent, 'info' and higher will impose the least overhead on
     * production applications.
     */
    level: "info",
    filepath: "stdout",
  },

};
```

**Comment by vasanthi-d** [comment]
@sebastianmulders - I am exactly in the same boat as you and trying to get New Relic integrated with next.js when using standalone Next.js server.

I tried your above solution and when I am trying to deploy to Kubernetes, pod is not coming up and getting below error. I only added `"@newrelic/next": "^0.3.0"` as dependency in my package.json.  Am I missing any dependency in  my `unstable_includeFiles` ?  How did you determine the dependencies to include in `unstable_includeFiles`?

```
Error: Cannot find module 'newrelic'
Require stack:
- /usr/src/app/node_modules/@newrelic/next/index.js
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@newrelic/next/index.js:13:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@newrelic/next/index.js',
    'internal/preload'
  ]
}
```

**Comment by vasanthi-d** [comment]
@sebastianmulders  - do we have to configure newrelic.js?

**Comment by sebastianmulders** [comment]
> I tried your above solution and when I am trying to deploy to Kubernetes, pod is not coming up and getting below error. I only added `"@newrelic/next": "^0.3.0"` as dependency in my package.json. Am I missing any dependency in my `unstable_includeFiles` ? How did you determine the dependencies to include in `unstable_includeFiles`?

You could try adding newrelic as a dependency (e.g. just by doing `yarn add newrelic`). If that doesn't work, try to add it to `instable_includeFiles` too, although that's not needed in my setup.

I've determined the files to include in `unstable_includeFiles` just by trial and error. Starting with an empty list, check whether it runs, see why it fails, update the list and repeat. Until at some point it runs.

And yes, I'd advise you to configure `newrelic.js`, but I believe it's optional.

**Comment by vasanthi-d** [comment]
@sebastianmulders - thank you so much for your timely response. I installed `'newrelic'` explicitly and it worked fine. I didn't have to configure ` newrelic.js`.
Question - With this approach, we are seeing `'service' / 'node'` based activity in New Relic.  Do we need to anything else to log browser based events/metrics?

**Comment by sebastianmulders** [comment]
@vasanthi-d to log browser based events and metrics, you should take a look at the [Client-side Instrumentation docs](https://github.com/newrelic/newrelic-node-nextjs#client-side-instrumentation).

**Comment by YutaMoriJP** [comment]
So I guess there is no good way to run `@newrelic/next` with nextjs standalone mode...? Makes it unusable tbh

**Comment by YutaMoriJP** [comment]
OK this is the setup that worked best for me using standalone output.

**Comment by dodyagung** [comment]
> ```
> export async function register() {
>   if (process.env.NEXT_RUNTIME === 'nodejs') {
>     await import('@newrelic/next');
>   }
> }
> ```

I got an error with this : 

> Type error: Could not find a declaration file for module '@newrelic/next'. '/app/node_modules/.pnpm/@newrelic+next@0.8.0_newrelic@11.13.0/node_modules/@newrelic/next/index.js' implicitly has an 'any' type.

Then I try to change `import` to `require`, and it works 👍

**Comment by YutaMoriJP** [comment]
@dodyagung 
Hmm I think you just need to add a declaration file for newrelic. Something like this:
```js 
// newrelic.d.ts
declare module '@newrelic/next' {
}
```

**Comment by raph90** [comment]
Unfortunately this is still really not working for me. Here's my files:

```ts
// instrumentation.ts
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    //@ts-ignore
    await import('@newrelic/next');
  }
}
```
next.config.js
```js
const bundleAnalyzer = require('@next/bundle-analyzer');
const nrExternals = require('@newrelic/next/load-externals');

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  reactStrictMode: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
  webpack: nrExternals,
  experimental: {
    optimizePackageImports: ['@mantine/core', '@mantine/hooks', '@mantine/form', '@mantine/dates'],
    instrumentationHook: true,
    serverActions: {
      allowedOrigins: ['localhost:3000'],
    },
    serverComponentsExternalPackages: ['newrelic'],
  },
  output: 'standalone',
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'my-site.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
});

```
I've also tried moving the import statement into a route handler based on conversation here:
https://github.com/vercel/next.js/issues/49897

It's not worked in either case, I'm still getting 
```
Error: Cannot find module '@newrelic/next'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at internalRequire (node:internal/modules/cjs/loader:176:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1563:5)
    at loadPreloadModules (node:internal/process/pre_execution:730:5)
    at setupUserModules (node:internal/process/pre_execution:206:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.13.1
```
