### ISSUE TITLE
How to include newrelic in the browser for error handling

### ISSUE THREAD

**Issue by siuvdlec** [newrelic/newrelic-node-nextjs#74]
## Is your feature request related to a problem? Please describe.
In the `Error Handling` documentation section [Error Handling](https://github.com/newrelic/newrelic-node-nextjs#error-handling) it is not clear how `newrelic` is included in the browser. Which is the suggested method?

**Comment by bizob2828** [comment]
@siuvdlec this line calls out how it is included in the browser.

>  The example above assumes that both the New Relic Browser and Node.js agents are integrated

The section right above it call out how to intergrate the browser agent
