### ISSUE TITLE
Docs client-side instrumentation is not working

### ISSUE THREAD

**Issue by billysutomo** [newrelic/newrelic-node-nextjs#87]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I try implement nextjs monitoring from server to client side. Server side is working fine, but when implement client side i got error on `_document.ts`. even got error, when run `yarn dev` still running and sent error. But if run `yarn build` will get error

![image](https://user-images.githubusercontent.com/17403088/193329305-489a430e-bf5c-496a-9111-7427749c7642.png)

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
can compile, or `yarn build`

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
1. implement client side instrumentation following docs https://github.com/newrelic/newrelic-node-nextjs#client-side-instrumentation

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: v16.13.2
* WSL ubuntu 20.00
* package.json
```
{
  "name": "----",
  "author": "----",
  "license": "MIT",
  "version": "1.0.0-6",
  "private": true,
  "repository": {
    "type": "git",
    "url": "----"
  },
  "scripts": {
    "dev": "NODE_OPTIONS='-r @newrelic/next' next dev",
    "build": "next build",
    "start": "NODE_OPTIONS='-r @newrelic/next' next start",
    "lint": "eslint --fix .",
    "prepare": "husky install",
    "storybook": "start-storybook -p 9009",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@emotion/css": "^11.10.0",
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@mui/material": "^5.4.4",
    "@newrelic/next": "^0.3.0",
    "@newrelic/publish-sourcemap": "^5.1.0",
    "@next/bundle-analyzer": "^12.2.4",
    "@sentry/nextjs": "^6.19.7",
    "amplitude-js": "^8.18.1",
    "axios": "^0.26.1",
    "cookie-cutter": "^0.2.0",
    "copy-to-clipboard": "^3.3.1",
    "date-fns": "^2.28.0",
    "dotenv": "^16.0.2",
    "env-cmd": "^10.1.0",
    "file-saver": "^2.0.5",
    "firebase": "^9.6.9",
    "libphonenumber-js": "^1.9.49",
    "moment": "^2.29.1",
    "newrelic": "^9.1.0",
    "next": "^12.2.5",
    "react": "17.0.2",
    "react-circular-progressbar": "^2.0.4",
    "react-dom": "17.0.2",
    "react-drag-drop-files": "^2.3.4",
    "react-easy-crop": "^4.1.3",
    "react-geolocated": "^3.2.0",
    "react-gtm-module": "^2.0.11",
    "react-icomoon": "^2.4.9",
    "react-icons": "^4.3.1",
    "react-loader-spinner": "^6.0.0-0",
    "react-redux": "^7.2.6",
    "react-shimmer-effects": "^1.0.2",
    "react-textarea-autosize": "^8.3.3",
    "react-transition-group": "^4.4.5",
    "redux": "^4.1.2",
    "redux-devtools-extension": "^2.13.9",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "sharp": "^0.30.7",
    "styled-components": "^5.3.3",
    "swiper": "^8.0.6",
    "uuid": "^8.3.2",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-controls": "^6.4.19",
    "@storybook/addon-docs": "^6.4.19",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/addon-viewport": "^6.4.19",
    "@storybook/builder-webpack5": "^6.4.19",
    "@storybook/manager-webpack5": "^6.4.19",
    "@storybook/react": "^6.4.19",
    "@types/node": "^17.0.21",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "@types/react-transition-group": "^4.4.5",
    "@types/redux-logger": "^3.0.9",
    "@types/styled-components": "^5.1.23",
    "@typescript-eslint/eslint-plugin": "^5.32.0",
    "eslint": "8.9.0",
    "eslint-config-next": "12.1.0",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "typescript": "^4.6.2"
  },
  "resolutions": {
    "webpack": "^5"
  }
}
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by johngribbin** [comment]
@billysutomo can you share your entire `_document.ts` file?

**Comment by billysutomo** [comment]
@johngribbin Hi.
I implement your code and It's working now.
Thanks!
