### ISSUE TITLE
Clarification on next/script usage

### ISSUE THREAD

**Issue by willwill96** [newrelic/newrelic-node-nextjs#92]
## Is your feature request related to a problem?
Not really a problem.

## ~Feature~ Description
The docs state for the browser agent script:
> The most appropriate approach would be to follow the [beforeInteractive strategy](https://nextjs.org/docs/basic-features/script#beforeinteractive). Put the following in your pages/_document.ts

I am wondering if you could expand on why this is the most appropriate strategy. In one of my apps, I've moved the new relic script to a shared layout component and changed it to an `afterInteractive` . Things _seem_ to be working with a lift in web vitals. Would you expect any issues from taking this approach?

## Describe Alternatives
N/A

## Additional context
N/A
## Priority
Please help us better understand this feature request by choosing a priority from the following options:
Nice to Have

**Comment by bizob2828** [comment]
Hi @willwill96 by changing the script to be afterInteractive you may be missing events around any scripts tha tare loaded before the bundled Next.js javascript.  It may not be applicable to you though.  You can read more about the differences here: https://nextjs.org/docs/basic-features/script#beforeinteractive
