### ISSUE TITLE
Guidance on Usage with Vercel?

### ISSUE THREAD

**Issue by stephenhmarsh** [newrelic/newrelic-node-nextjs#94]
## Is your feature request related to a problem? Please describe.

So the docs say:
> If you cannot control how your program is run, you can load the @newrelic/next module before any other module in your program. However, we strongly suggest you avoid this method at all costs. We found bundling when running next build causes problems and also will make your bundle unnecessarily large.

Does that mean there's no way forward on Vercel? Seems with Next 13, instrumenting server-side is only going to become more important?

## Feature Description

We want to instrument on Vercel, but not sure how. Surprisingly there's no other issues mentioning this. 

## Describe Alternatives
n/a

## Additional context
n/a

## Priority
Please help us better understand this feature request by choosing a priority from the following options:
[Nice to Have, Really Want, Must Have, Blocker]
Blocker

**Comment by bizob2828** [comment]
Hi @stephenhmarsh, unfortunately we do not have a quick answer.  But based on this ask and #88, I'm going to ask our PM to prioritize a research spike to handle these newer deployment models of Next.js.  If Vercel has a way to pass env vars to your running Next.js service you should be able to use `NODE_OPTIONS='-r @newrelic/next'`

**Comment by stephenhmarsh** [comment]
Thanks @bizob2828 -- yes it's similar to #88 -- there's no way to run a custom start command when deploying on Vercel 😞 , which has been a blocker for us on a Next 12 app. That's what I was surprised more people don't mention :)

You are correct Next 13 and its new Server Components were only officially announced/released on Tuesday.

**Comment by stephenhmarsh** [comment]
@bizob2828 ah thanks, brain fart. so even with that set, i'm not able to get past the build phase (see logs below). [ I installed both `@newrelic/next` and its peer `newrelic` ](https://gist.github.com/stephenhmarsh/40783983433446a76045c5e6cc21276a)


```
13:56:32.231 | Cloning github.com/stephenhmarsh/met-sanity (Branch: main, Commit: 9aa7eda)
-- | --
13:56:39.835 | Cloning completed: 7.604s
13:56:40.137 | internal/modules/cjs/loader.js:905
13:56:40.137 | throw err;
13:56:40.137 | ^
13:56:40.137 |  
13:56:40.137 | Error: Cannot find module '@newrelic/next'
13:56:40.137 | Require stack:
13:56:40.138 | - internal/preload
13:56:40.138 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
13:56:40.138 | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
13:56:40.138 | at Module.require (internal/modules/cjs/loader.js:974:19)
13:56:40.138 | at Module._preloadModules (internal/modules/cjs/loader.js:1244:12)
13:56:40.138 | at loadPreloadModules (internal/bootstrap/pre_execution.js:475:5)
13:56:40.139 | at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:72:3)
13:56:40.139 | at internal/main/run_main_module.js:7:1 {
13:56:40.139 | code: 'MODULE_NOT_FOUND',
13:56:40.139 | requireStack: [ 'internal/preload' ]
13:56:40.141 | }
13:56:40.142 | Sandbox exited with code 1 and signal null

```

**Comment by bizob2828** [comment]
@stephenhmarsh you don't want to pass anything into the build phase. You want to set that `NODE_OPTIONS='-r @newrelic/next'` on the deployed code.  I don't know the mechanics of vercel but I hope the build phase is detached from deploy and you can vary what get sets when.

**Comment by stephenhmarsh** [comment]
Ah yes.  Thanks for that. (Sorry my memory is fuzzy because I'm revisiting this and attempting to do this for the 2nd time after getting nowhere a few weeks ago and setting this aside).

So Vercel does organize things with separate install/build/run phases, at least.  But weirdly setting NODE_OPTIONS="" for `Build` does not "override" and change this behavior? ( I still get same error as above )

<img width="984" alt="Screen Shot 2022-10-27 at 2 25 38 PM" src="https://user-images.githubusercontent.com/6576730/198370168-32a14062-c4eb-47f8-b7ef-0c614e213df4.png">

**Comment by bizob2828** [comment]
@stephenhmarsh I'm not suggesting to even override the build command.  i don't see a run command override but that's where you want to put it.  You should not have any reference to `@newrelic/next` in your next.js app just in package.json

**Comment by stephenhmarsh** [comment]
Yeah, I follow you and it's super helpful! 

Unfortunately Build/Release/Run (aka "Start") all share the same project-wide ENV.  So to get `NODE_OPTIONS='-r @newrelic/next'` out of the Build phase, I thought I could pass `NODE_OPTIONS=""` but apparently not. 

Would would be great is if I could `NODE_OPTIONS=...` during Run/Start command but thats exactly the one that they don't let you customize. :(

**Comment by bizob2828** [comment]
> Yeah, I follow you and it's super helpful!
> 
> Unfortunately Build/Release/Run (aka "Start") all share the same project-wide ENV. So to get `NODE_OPTIONS='-r @newrelic/next'` out of the Build phase, I thought I could pass `NODE_OPTIONS=""` but apparently not.
> 
> Would would be great is if I could `NODE_OPTIONS=...` during Run/Start command but thats exactly the one that they don't let you customize. :(

Blah. I really wish these providers made it easier on instrumentation vendors 😄 .  We will follow up once we have the time to do research/hack around on our end.

**Comment by stephenhmarsh** [comment]
I totally agree -- the Vercel platform is too opaque and it shouldn't be this hard to get observability that works pretty much turn-key anywhere else. Anyway, thanks for your help and for looking into this. Looking forward to hearing back.

**Comment by stephenhmarsh** [comment]
See also: https://github.com/vercel/community/discussions/1067

**Comment by aacitelli** [comment]
Any updates on this? I've followed most of the above and can't seem to get anything to work. I'm trying to get APM capability for serverless backend functions in something like NewRelic or Datadog and can't seem to get anything more than logs from Vercel.

**Comment by stephenhmarsh** [comment]
Sadly it's not in the APM yet. It's just the logs drains from Vercel's log drains API.  Anyone on this thread could've written it. I suspect the reason is basically "javascript"

**Comment by bmamone** [comment]
I'm also waiting for the Traces integration.

![Screenshot 2023-02-23 at 08 11 10](https://user-images.githubusercontent.com/2811006/220890762-86f156e8-aae4-4c73-86a4-5f2867011f46.png)

Traces can be enabled (even though in Beta) on the dashboard. That is misleading, as it's not working at all.

**Comment by ZacxDev** [comment]
I am also struggling with this

**Comment by bizob2828** [comment]
Hi @bmamone and @ZacxDev this Traces(Beta) feature is not associated with the New Relic Node.js agent team, but instead their own [integration](https://vercel.com/integrations/newrelic).  I would reach out to them for questions around this feature.  We do have time slotted soon to do research on our end to figure out how to use our Next.js instrumentation in Vercel.

**Comment by stephenhmarsh** [comment]
> I'm also waiting for the Traces integration.
> 
> ![Screenshot 2023-02-23 at 08 11 10](https://user-images.githubusercontent.com/2811006/220890762-86f156e8-aae4-4c73-86a4-5f2867011f46.png)
> 
> Traces can be enabled (even though in Beta) on the dashboard. That is misleading, as it's not working at all.

@bmamone You will also need to follow their documentation for setting up Open Telemetry to report to Traces, if you haven't yet: https://vercel.com/docs/concepts/observability/otel-overview/quickstart

**Comment by ZacxDev** [comment]
> Hi @bmamone and @ZacxDev this Traces(Beta) feature is not associated with the New Relic Node.js agent team, but instead their own [integration](https://vercel.com/integrations/newrelic). I would reach out to them for questions around this feature. We do have time slotted soon to do research on our end to figure out how to use our Next.js instrumentation in Vercel.

I'm referring to the NODE_OPTIONS env var issue, it seems I need to set that var to have newrelic agent work correctly, but when I do that the vercel build breaks. (The same issue previous users have mentioned in this thread)

**Comment by bmamone** [comment]
@ZacxDev Actually `NODE_OPTIONS='-r @newrelic/next'` is what should be added on the **run** phase, not the **build** phase. Vercel does not let you customize run phase options, so that's why we can't set up NewRelic's agent. 

As far as I'm concerned, apart from setting up Open Telemetry reporting as @stephenhmarsh mentioned, there's no way of easily reporting APM tracing to NewRelic from a Next.js default deployment to Vercel as of today.

@bizob2828 Thanks for the clarification. For some reason I tought NewRelic was responsible for the integration. Will check on Vercel's discussion for updates.

**Comment by bizob2828** [comment]
We are eager to dig into this. It's bubbling to the top of our queue shortly.  Thanks all for your patience

**Comment by w33ts** [comment]
Same here, his is a huge blocker for us instrumenting our applications.

**Comment by mrickard** [comment]
@NathanHynes While we don't have an update yet, we're setting upcoming priorities, and we'll take this into account. Thank you for your patience!

**Comment by bizob2828** [comment]
I dug into this and cannot seem to figure out how to only control NODE_OPTIONS on deploy.  I have a question out [here](https://github.com/orgs/vercel/discussions/3982)

**Comment by NathanHynes** [comment]
Has anything happened since leaving the question? I noticed that someone mentioned comparing this tool to the way sentry is instrumented?

**Comment by bizob2828** [comment]
Hi @NathanHynes, the short answer is not really.  I had to [PR Next.js](https://github.com/vercel/next.js/pull/55412), and [our instrumentation](https://github.com/newrelic/newrelic-node-nextjs/pull/162).  However, even with all of that our instrumentation does not play nice in these cloud providers.  I have an internal document of the research but the tl;dr is we would have to create another product or explore using the OpenTelemetry spans Next.js produces.  We explored a hybrid agent to get prisma telemetry [here](https://github.com/newrelic/newrelic-node-opentelemetry-integration).  It was fairly successful and probably plan on revisiting this.  At the very least you could take advantage of the instrumentHook and setup an OTLP exporter to send the OpenTelemetry spans to New Relic. 

We plan on doing more research into these solutions in the future.  I also plan to document how to export the Otel spans with  OTLP exporter to New Relic.  Aside from that, there isn't any low hanging fruit here to address these issues.  The only cloud provider I was able to get this set up in with 0 issue was Azure Static Sites. But both Vercel and AWS Amplify have the same issues in that the code is split and the instrumentation we have is run on FaaS which our agent requires more work to function properly

**Comment by ThomasSalty** [comment]
Hi @bizob2828! I'm following this thread because I also have issues with New Relic integration in my Next.js app that's deployed on Vercel.

I have used [this guide](https://docs.newrelic.com/docs/logs/forward-logs/vercel-integration/) and using the following scripts in package.json the integration works fine running locally:
`"dev": "NODE_OPTIONS='-r @newrelic/next' next",`
`"start": "NODE_OPTIONS='-r @newrelic/next' next start",`

However, when I deploy the app to Vercel there's no option for supplying parameters to the `start` command and I believe that's the reason why I get this in my `<head>` section in Preview and Production deployments:
`<script type="text/javascript"><!-- NREUM: (4) --></script>`

Does that mean that the Vercel integration doesn't work at all? Or is it just me (and a few other people)?

**Comment by ThomasSalty** [comment]
I was not able to set the `NODE_OPTIONS='-r @newrelic/next'` environment variable to fix the `NREUM: (4)` error, no matter how many different ways I tried.

So I decided to just try the copy/paste method to install the browser monitoring agent pretty much like what's happening [in this repo](https://github.com/jesse-weaver/new-relic-agent-react/blob/master/src/index.js).
After customizing the parameters, it finally works in all 3 environments on Vercel. 🎉

**Comment by mrchief** [comment]
I just did the same and it's working for me. FWIW, I also have NewRelic integration enabled on Vercel and I didn't use their NPM package in my app at all.

**Comment by stephenhmarsh** [comment]
@ThomasSalty and @mrchief - that's great but for anyone following this Issue, we're talking about instrumenting the backend with the full APM, not the browser agent.

**Comment by mrchief** [comment]
Ah gotcha. For backend, I'm using https://docs.newrelic.com/docs/logs/forward-logs/vercel-integration/. Curious to know if you have tried it and if so, what are its shortcomings.

**Comment by stephenhmarsh** [comment]
@mrchief the log forwarding integration was fine but it was using a lot of our NewRelic data limits to send them, while providing basically the same insights we were already getting on our Axiom dashboard, so we turned them off. The data is useful but much less granular than the APM.

**Comment by baochanh18** [comment]
@mrchief 
Thank you for your guidance, but for me, it still doesn't work as I expected. I want to notice errors to New Relic when any errors occur on the frontend, but it did not do that. Even though I configured the environment locally and it worked correctly as I expected, I cannot do the same thing on Vercel. The key issue is that we cannot set NODE_OPTIONS when starting the program. 
I'm sure that the newrelic agent is installed correctly because on the website console, I typed `newrelic.noticeError`, and it ran successfully.
Now I feel really stuck.

**Comment by mrchief** [comment]
> I want to notice errors to New Relic when any errors occur on the frontend,

If you only want error monitoring and not everything else the NR has to offer, you can probably try alternatives like sentry.io.

**Comment by jswent** [comment]
Is there any update on this? I am not able to get APM to work with Vercel at all.

**Comment by ygerass** [comment]
Cannot prioritize this issue at the moment. Closing now, may reconsider later should the need persist.

**Comment by jswent** [comment]
The need does persist. This is a critical feature for monitoring any applications built with Next.js, as many other hosting providers have issues with it. If you're going to close this and say it's not important, then don't say it's completed.

**Comment by dacarey** [comment]
> Cannot prioritize this issue at the moment. Closing now, may reconsider later should the need persist.

“should the need persist” to monitor deployments to Vercel or Netlify.  Yes it very much does

**Comment by w33ts** [comment]
Vercel, Netlify, Cloudflare, etc. Our entire catalog of applications are unable to be instrumented. Especially with the edge runtime, but that is another issue altogether.

**Comment by ygerass** [comment]
Next.js has evolved since we added instrumentation. Most of the use cases are around deploying to cloud providers like Vercel, AWS Amplify, Netlify, Azure Static Sites, etc. Most of these providers do not allow you to control the run phase of Next.js CLI which is where we recommend registering the Next.js instrumentation. With that being said, our recommendation is to rely on the experimental instrumentationHook feature of Next.js and use OpenTelemetry and send the data to New Relic via OTLP ([gist reference](https://gist.github.com/bizob2828/a7d52ac69b7db6d8508c865aafa0b62b)).

#nr-dev

**Comment by andrewmclagan** [comment]
So the suggested solution is to setup an open-telemetry integration with the [NextJS instrumentation](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation) feature? 

If that is the case, what is the purpose of `@newrelic/next`?  Seems like this suggestion completely negates the purpose of this package. Why not just have this package integrate as such 🤣

**Comment by bizob2828** [comment]
@andrewmclagan the `@newrelic/next` instrumentation has hit its limits.  Our suggestion is to use Otel and we wanted to get out that gist for people looking for a solution.  We do have plans to update `@newrelic/next` to do what the gist suggests but we're a small team and we currently have other priorities.  PRs are always welcome thought.

**Comment by KunwarSingh** [comment]
Anyone able to run APM in Vercel? Found any way to do this set NODE_OPTIONS='-r @newrelic/next' && next start

I am able to run this in dev in local, and Browser Monitoring is also fine
