### ISSUE TITLE
[docs] Update docs to not require newrelic explict

### ISSUE THREAD

**Issue by fmacherey** [newrelic/newrelic-node-nextjs#98]
Hey guys, 

we figured out, that you also can require newrelic itself via `NODE_ENV=production node -r @newrelic/next -r newrelic server/index.js`. 

In the example for the error page, there is newrelic loaded via `const require`. Maybe it is more uniformed and clear, to have both packages plugged in with -r. 

This feature request is meant as to be discuss on this topic, and maybe adjust the docs accordingly. 

Thanks so far.

**Comment by bizob2828** [comment]
@fmacherey when you load `-r @newrwrelic/next` it loads the agent, you can see it [here](https://github.com/newrelic/newrelic-node-nextjs/blob/main/index.js#L13).  The error example is requiring the agent so you have access to the API within code. I'm unclear how you'd be able to call `newrelic.getBrowserTimingHeader` within a file without saving a reference to the agent.  Do you mind providing a repository demonstrating what you're saying or a code snippet?
