### ISSUE TITLE
Feature request: Browser agent script integration in SSG static pages

### ISSUE THREAD

**Issue by rdoi-ps** [newrelic/newrelic-node-nextjs#99]
## Is your feature request related to a problem? Please describe.
Newrelic browser agent integration doesn't work for build time "server side generated" static pages.

## Feature Description
A method to inject browser agent snippet in static pages generated with SSG.

I may be missing something, but it looks like `getBrowserTimingHeader` script injection method ([doc link](https://newrelic.github.io/node-newrelic/docs/API.html#getBrowserTimingHeader)) doesn't work for static pages rendered in build time (SSG). 

Noted the [foot note](https://github.com/newrelic/newrelic-node-nextjs/blob/main/docs/inject-browser-agent.md): "For static compiled pages, you can use the copy-paste method for enabling the New Relic browser agent."
We did manage to implement the "copy+paste" snippet to our SSG pages. 

However, for future snippet updates, we would be polling newrelic site and updating all our projects manually, what would be really bad for a maintainability aspect. 

It would be great if we could get updates directly from an official newrelic lib (npm `package.json` versioning).

## Describe Alternatives
Continue injecting the snippet with "copy+paste" method.

## Additional context
N/A

## Priority
Really Want

**Comment by bizob2828** [comment]
Hi @rdoi-ps, have you read through this blog post https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data?  There's also an [example in action](https://github.com/newrelic-experimental/newrelic-nextjs-integration)

**Comment by rdoi-ps** [comment]
> Hi @rdoi-ps, have you read through this [blog post](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data)? There's also an [example in action](https://github.com/newrelic-experimental/newrelic-nextjs-integration)

Hi @bizob2828, for what I saw the article guides through the same example shown here (injecting `browserTimingHeader()`). 
It works fine when running in NextJS with normal server side processing.

But if you setup NextJS to generate static pages (SSG) and build the project, the `browserTimingHeader()` method just returns a script placeholder (like `<script><!-- NREUM: (0) --></script>`) and not the script itself. 

For what I understood, the generated script includes a kind of transaction/session id from the request to somehow link reports from the server and the client. 

By building static pages in SSG, we do not have "request context" so no "transaction id" is available.

**Comment by bizob2828** [comment]
> > Hi @rdoi-ps, have you read through this [blog post](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data)? There's also an [example in action](https://github.com/newrelic-experimental/newrelic-nextjs-integration)
> 
> Hi @bizob2828, for what I saw the article guides through the same example shown here (injecting `browserTimingHeader()`). It works fine when running in NextJS with normal server side processing.
> 
> But if you setup NextJS to generate static pages (SSG) and build the project, the `browserTimingHeader()` method just returns a script placeholder (like `<script><!-- NREUM: (0) --></script>`) and not the script itself.
> 
> For what I understood, the generated script includes a kind of transaction/session id from the request to somehow link reports from the server and the client.
> 
> By building static pages in SSG, we do not have "request context" so no "transaction id" is available.

Ah you're right.  Yea we will never be able to auto inject without that.  The copy past method may be the only option for static pages unless we remove that checking of transaction context, but not sure that's possible

**Comment by bizob2828** [comment]
@rdoi-ps we have added a [FAQ](https://github.com/newrelic/newrelic-node-nextjs/blob/ea20b76a13c84f4f3c48e9544e18e568b8e41c33/docs/faqs/browser-agent.md) that links out to working examples of injecting browser agent into Pages and App Router Next.js applications.  I'm going to close this.
